# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "38f20c3131b02df064c038805c458e8a"
name = "Plastic Free Club Discounts"
handle = "plastic-free-club-discounts"
application_url = "https://plastic-free-club-discounts.onrender.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_discounts,write_products"

[auth]
redirect_urls = [ "https://plastic-free-club-discounts.onrender.com/auth/callback" ]

[pos]
embedded = false
